<div class="alert alert-success" role="alert">
  <h1 class="alert-heading">Análisis Vibracional</h1>
  <h3 class="alert-heading">Prof. Enrique Mejía Ospino, emejia@uis.edu.co</h3>
  <h4 class="alert-heading">Escuela de Química</h4>
  <h4 class="alert-heading">Universidad Industrial de Santander</h4>
  </div>

**<font color=red> Vamos  atilizar el modulo *PSI4* para desarrollar algunos ejercicios de cálculo mecánico-cuántico. En este Cuaderno de Jupyter Realizaremos el Análisis Vibracional utilizando el paquete desarrollado por el Prof. Tom Allison. *Advertencia: Cada vez que se requiera ejecutar un calculo con este paquete, se debe reiniciar el kernel*.** 

In [2]:
import psi4
import numpy as np
import matplotlib.pyplot as plt
import fortecubeview # Visualizar moléculas
import h5py
import pandas as pd
import CHE525_Vib as vib
#from qcelemental import Datum
%matplotlib inline

**<font color=green> Inicializamos las condiciones de maquina.** 

In [3]:
psi4.core.clean()
psi4.core.clean_options()
psi4.set_memory('2000 MB')  # Memoria que sera utilizada en el cálculo
psi4.set_num_threads(8)    # Cnatida de hilos a utilzar, tener en cuenta que un núcleo soporta 24 hilos 


  Memory set to   1.863 GiB by Python driver.
  Threads set to 8 by Python driver.


**<font color=green>Podemos realizar los mismos calculos sobre el ángulo *H-O-H* y graficar los resultados.** 

In [4]:
psi4.core.set_output_file('./Data/H2O_Vib.dat', False) # Archivo de salida
# Vamos a definir otra forma de flexibilizar unos de los parámetros structurales, en este casp el ángulo
# entre los hidrógeno, utilizamos el formato Z-matrix
HOH_v= """
    o
 h   1 ho2     
 h    1 ho3         2 hoh3      

ho2=        0.95
ho3=        0.95
hoh3=       107.0"""

# Método de Cálculo
method='scf/6-31G*'

# Definimos la geometría de la molécula de acuerdo psi4  
HOH = psi4.geometry(HOH_v) 

# Optimizamos la geometría
E0, wfn0 = psi4.optimize(method, molecule = HOH, return_wfn = True) # optimización inicial

# visualización de los modos normales de vibración.
psi4.set_options({"normal_modes_write": True})

# Adiciona algunos caracteres al nombre del archivo de salida 
psi4.set_options({"writer_file_label": "h2o-hf"})

# Calcula la frecuencias usando la geometría optimizada
psi4.frequencies(method)
vib_results = {}
# Calculamos las intensidades IR usand el paquete CHE525_vib desarrollado por el Prof. Tom Allison de 
# Stony Brook University, la función eps ajusta los pasos!
vib_results = vib.dipder(method,HOH, eps = 0.01)

# Mostramos los resultados en pantalla
vib=[(np.array(vib_results['om'])).real, np.array(vib_results['IR_Intensity'])]
Results_vib = pd.DataFrame(vib).T.set_axis(['cm^-1', 'IR active [km/mol]'], axis=1, inplace=False)
Results_vib 
# Convertimos a DataFrame y Guardamos el archivo!
#Results_vib.to_excel('vib_results.csv')

Optimizer: Optimization complete!


/home/emejia/Documents/QC_Notebook/CHE525_Vib.py:25: FutureWarning: Using scalar QCVariable ` DIPOLE X` [D] instead of array ` DIPOLE` [e a0] is deprecated, and in 1.5 it will stop working

  D[0] = wfn_in.variable(' DIPOLE X')
/home/emejia/Documents/QC_Notebook/CHE525_Vib.py:26: FutureWarning: Using scalar QCVariable ` DIPOLE Y` [D] instead of array ` DIPOLE` [e a0] is deprecated, and in 1.5 it will stop working

  D[1] = wfn_in.variable(' DIPOLE Y')
/home/emejia/Documents/QC_Notebook/CHE525_Vib.py:27: FutureWarning: Using scalar QCVariable ` DIPOLE Z` [D] instead of array ` DIPOLE` [e a0] is deprecated, and in 1.5 it will stop working

  D[2] = wfn_in.variable(' DIPOLE Z')


Initial dipole:
[0.         0.         0.86511907]
Working on mode 6 with frequency (1826.6144622158488+0j)


/home/emejia/Documents/QC_Notebook/CHE525_Vib.py:25: FutureWarning: Using scalar QCVariable ` DIPOLE X` [D] instead of array ` DIPOLE` [e a0] is deprecated, and in 1.5 it will stop working

  D[0] = wfn_in.variable(' DIPOLE X')
/home/emejia/Documents/QC_Notebook/CHE525_Vib.py:26: FutureWarning: Using scalar QCVariable ` DIPOLE Y` [D] instead of array ` DIPOLE` [e a0] is deprecated, and in 1.5 it will stop working

  D[1] = wfn_in.variable(' DIPOLE Y')
/home/emejia/Documents/QC_Notebook/CHE525_Vib.py:27: FutureWarning: Using scalar QCVariable ` DIPOLE Z` [D] instead of array ` DIPOLE` [e a0] is deprecated, and in 1.5 it will stop working

  D[2] = wfn_in.variable(' DIPOLE Z')


D1 = 
[0.        0.        0.8684319]
Working on mode 7 with frequency (4070.306766552159+0j)


/home/emejia/Documents/QC_Notebook/CHE525_Vib.py:25: FutureWarning: Using scalar QCVariable ` DIPOLE X` [D] instead of array ` DIPOLE` [e a0] is deprecated, and in 1.5 it will stop working

  D[0] = wfn_in.variable(' DIPOLE X')
/home/emejia/Documents/QC_Notebook/CHE525_Vib.py:26: FutureWarning: Using scalar QCVariable ` DIPOLE Y` [D] instead of array ` DIPOLE` [e a0] is deprecated, and in 1.5 it will stop working

  D[1] = wfn_in.variable(' DIPOLE Y')
/home/emejia/Documents/QC_Notebook/CHE525_Vib.py:27: FutureWarning: Using scalar QCVariable ` DIPOLE Z` [D] instead of array ` DIPOLE` [e a0] is deprecated, and in 1.5 it will stop working

  D[2] = wfn_in.variable(' DIPOLE Z')


D1 = 
[0.         0.         0.86374229]
Working on mode 8 with frequency (4188.62278792277+0j)
D1 = 
[0.         0.00244304 0.8651162 ]


/home/emejia/Documents/QC_Notebook/CHE525_Vib.py:25: FutureWarning: Using scalar QCVariable ` DIPOLE X` [D] instead of array ` DIPOLE` [e a0] is deprecated, and in 1.5 it will stop working

  D[0] = wfn_in.variable(' DIPOLE X')
/home/emejia/Documents/QC_Notebook/CHE525_Vib.py:26: FutureWarning: Using scalar QCVariable ` DIPOLE Y` [D] instead of array ` DIPOLE` [e a0] is deprecated, and in 1.5 it will stop working

  D[1] = wfn_in.variable(' DIPOLE Y')
/home/emejia/Documents/QC_Notebook/CHE525_Vib.py:27: FutureWarning: Using scalar QCVariable ` DIPOLE Z` [D] instead of array ` DIPOLE` [e a0] is deprecated, and in 1.5 it will stop working

  D[2] = wfn_in.variable(' DIPOLE Z')


cm^-1  IR active [km/mol]
0  1826.614462          106.991344
1  4070.306767           18.479164
2  4188.622788           58.185038

In [6]:
vib_results

{'dipder': [array([0.        , 0.        , 0.33128267]),
  array([ 0.        ,  0.        , -0.13767832]),
  array([ 0.        ,  0.24430354, -0.00028698])],
 'om': [(1826.6144622158488+0j),
  (4070.306766552159+0j),
  (4188.62278792277+0j)],
 'IR_Intensity': [106.99134396605204, 18.479163883782483, 58.185038180021465]}